// Code generated by generate-keycodes. DO NOT EDIT.
package usagepages

const (
	KeyErrorRollOver         uint8 = 0x1  // Keyboard ErrorRollOver
	KeyPostfail              uint8 = 0x2  // Keyboard POSTFail
	KeyErrorUndefined        uint8 = 0x3  // Keyboard ErrorUndefined
	KeyA                     uint8 = 0x4  // Keyboard a and A
	KeyB                     uint8 = 0x5  // Keyboard b and B
	KeyC                     uint8 = 0x6  // Keyboard c and C
	KeyD                     uint8 = 0x7  // Keyboard d and D
	KeyE                     uint8 = 0x8  // Keyboard e and E
	KeyF                     uint8 = 0x9  // Keyboard f and F
	KeyG                     uint8 = 0xa  // Keyboard g and G
	KeyH                     uint8 = 0xb  // Keyboard h and H
	KeyI                     uint8 = 0xc  // Keyboard i and I
	KeyJ                     uint8 = 0xd  // Keyboard j and J
	KeyK                     uint8 = 0xe  // Keyboard k and K
	KeyL                     uint8 = 0xf  // Keyboard l and L
	KeyM                     uint8 = 0x10 // Keyboard m and M
	KeyN                     uint8 = 0x11 // Keyboard n and N
	KeyO                     uint8 = 0x12 // Keyboard o and O
	KeyP                     uint8 = 0x13 // Keyboard p and P
	KeyQ                     uint8 = 0x14 // Keyboard q and Q
	KeyR                     uint8 = 0x15 // Keyboard r and R
	KeyS                     uint8 = 0x16 // Keyboard s and S
	KeyT                     uint8 = 0x17 // Keyboard t and T
	KeyU                     uint8 = 0x18 // Keyboard u and U
	KeyV                     uint8 = 0x19 // Keyboard v and V
	KeyW                     uint8 = 0x1a // Keyboard w and W
	KeyX                     uint8 = 0x1b // Keyboard x and X
	KeyY                     uint8 = 0x1c // Keyboard y and Y
	KeyZ                     uint8 = 0x1d // Keyboard z and Z
	Key1                     uint8 = 0x1e // Keyboard 1 and !
	Key2                     uint8 = 0x1f // Keyboard 2 and @
	Key3                     uint8 = 0x20 // Keyboard 3 and #
	Key4                     uint8 = 0x21 // Keyboard 4 and $
	Key5                     uint8 = 0x22 // Keyboard 5 and %
	Key6                     uint8 = 0x23 // Keyboard 6 and ∧
	Key7                     uint8 = 0x24 // Keyboard 7 and &
	Key8                     uint8 = 0x25 // Keyboard 8 and *
	Key9                     uint8 = 0x26 // Keyboard 9 and (
	Key0                     uint8 = 0x27 // Keyboard 0 and )
	KeyEnter                 uint8 = 0x28 // Keyboard Return (ENTER)
	KeyEsc                   uint8 = 0x29 // Keyboard ESCAPE
	KeyBackspace             uint8 = 0x2a // Keyboard DELETE (Backspace)
	KeyTab                   uint8 = 0x2b // Keyboard Tab
	KeySpacebar              uint8 = 0x2c // Keyboard Spacebar
	KeyMinus                 uint8 = 0x2d // Keyboard - and (underscore)
	KeyEqual                 uint8 = 0x2e // Keyboard = and +
	KeyLeftBracket           uint8 = 0x2f // Keyboard [ and {
	KeyRightBracket          uint8 = 0x30 // Keyboard ] and }
	KeyBackslash             uint8 = 0x31 // Keyboard \ and \
	KeyNonUssharp            uint8 = 0x32 // Keyboard Non-US # and ˜
	KeySemicolon             uint8 = 0x33 // Keyboard ; and :
	KeyCode34                uint8 = 0x34 // Keyboard ‘ and “
	KeyGraveAccent           uint8 = 0x35 // Keyboard Grave Accent and Tilde
	KeyComma                 uint8 = 0x36 // Keyboard , and <
	KeyPeriod                uint8 = 0x37 // Keyboard . and >
	KeySlash                 uint8 = 0x38 // Keyboard / and ?
	KeyCapsLock              uint8 = 0x39 // Keyboard Caps Lock
	KeyF1                    uint8 = 0x3a // Keyboard F1
	KeyF2                    uint8 = 0x3b // Keyboard F2
	KeyF3                    uint8 = 0x3c // Keyboard F3
	KeyF4                    uint8 = 0x3d // Keyboard F4
	KeyF5                    uint8 = 0x3e // Keyboard F5
	KeyF6                    uint8 = 0x3f // Keyboard F6
	KeyF7                    uint8 = 0x40 // Keyboard F7
	KeyF8                    uint8 = 0x41 // Keyboard F8
	KeyF9                    uint8 = 0x42 // Keyboard F9
	KeyF10                   uint8 = 0x43 // Keyboard F10
	KeyF11                   uint8 = 0x44 // Keyboard F11
	KeyF12                   uint8 = 0x45 // Keyboard F12
	KeyPrintScreen           uint8 = 0x46 // Keyboard PrintScreen
	KeyScrollLock            uint8 = 0x47 // Keyboard Scroll Lock
	KeyPause                 uint8 = 0x48 // Keyboard Pause
	KeyInsert                uint8 = 0x49 // Keyboard Insert
	KeyHome                  uint8 = 0x4a // Keyboard Home
	KeyPageUp                uint8 = 0x4b // Keyboard PageUp
	KeyDeleteForward         uint8 = 0x4c // Keyboard Delete Forward
	KeyEnd                   uint8 = 0x4d // Keyboard End
	KeyPageDown              uint8 = 0x4e // Keyboard PageDown
	KeyRightArrow            uint8 = 0x4f // Keyboard RightArrow
	KeyLeftArrow             uint8 = 0x50 // Keyboard LeftArrow
	KeyDownArrow             uint8 = 0x51 // Keyboard DownArrow
	KeyUpArrow               uint8 = 0x52 // Keyboard UpArrow
	KeyKeypadNumLockAndClear uint8 = 0x53 // Keypad Num Lock and Clear
	KeyCode54                uint8 = 0x54 // Keypad /
	KeyCode55                uint8 = 0x55 // Keypad *
	KeyCode56                uint8 = 0x56 // Keypad -
	KeyCode57                uint8 = 0x57 // Keypad +
	KeyKeypadEnter           uint8 = 0x58 // Keypad ENTER
	KeyKeypad1AndEnd         uint8 = 0x59 // Keypad 1 and End
	KeyKeypad2AndDownArrow   uint8 = 0x5a // Keypad 2 and Down Arrow
	KeyKeypad3AndPageDn      uint8 = 0x5b // Keypad 3 and PageDn
	KeyKeypad4AndLeftArrow   uint8 = 0x5c // Keypad 4 and Left Arrow
	KeyKeypad5               uint8 = 0x5d // Keypad 5
	KeyKeypad6AndRightArrow  uint8 = 0x5e // Keypad 6 and Right Arrow
	KeyKeypad7AndHome        uint8 = 0x5f // Keypad 7 and Home
	KeyKeypad8AndUpArrow     uint8 = 0x60 // Keypad 8 and Up Arrow
	KeyKeypad9AndPageUp      uint8 = 0x61 // Keypad 9 and PageUp
	KeyKeypad0AndInsert      uint8 = 0x62 // Keypad 0 and Insert
	KeyCode63                uint8 = 0x63 // Keypad . and Delete
	KeyNonUsbackslash        uint8 = 0x64 // Keyboard Non-US \ and \
	KeyApplication           uint8 = 0x65 // Keyboard Application
	KeyPower                 uint8 = 0x66 // Keyboard Power
	KeyCode67                uint8 = 0x67 // Keypad =
	KeyF13                   uint8 = 0x68 // Keyboard F13
	KeyF14                   uint8 = 0x69 // Keyboard F14
	KeyF15                   uint8 = 0x6a // Keyboard F15
	KeyF16                   uint8 = 0x6b // Keyboard F16
	KeyF17                   uint8 = 0x6c // Keyboard F17
	KeyF18                   uint8 = 0x6d // Keyboard F18
	KeyF19                   uint8 = 0x6e // Keyboard F19
	KeyF20                   uint8 = 0x6f // Keyboard F20
	KeyF21                   uint8 = 0x70 // Keyboard F21
	KeyF22                   uint8 = 0x71 // Keyboard F22
	KeyF23                   uint8 = 0x72 // Keyboard F23
	KeyF24                   uint8 = 0x73 // Keyboard F24
	KeyExecute               uint8 = 0x74 // Keyboard Execute
	KeyHelp                  uint8 = 0x75 // Keyboard Help
	KeyMenu                  uint8 = 0x76 // Keyboard Menu
	KeySelect                uint8 = 0x77 // Keyboard Select
	KeyStop                  uint8 = 0x78 // Keyboard Stop
	KeyAgain                 uint8 = 0x79 // Keyboard Again
	KeyUndo                  uint8 = 0x7a // Keyboard Undo
	KeyCut                   uint8 = 0x7b // Keyboard Cut
	KeyCopy                  uint8 = 0x7c // Keyboard Copy
	KeyPaste                 uint8 = 0x7d // Keyboard Paste
	KeyFind                  uint8 = 0x7e // Keyboard Find
	KeyMute                  uint8 = 0x7f // Keyboard Mute
	KeyVolumeUp              uint8 = 0x80 // Keyboard Volume Up
	KeyVolumeDown            uint8 = 0x81 // Keyboard Volume Down
	KeyLockingCapsLock       uint8 = 0x82 // Keyboard Locking Caps Lock
	KeyLockingNumLock        uint8 = 0x83 // Keyboard Locking Num Lock
	KeyLockingScrollLock     uint8 = 0x84 // Keyboard Locking Scroll Lock
	KeyKeypadComma           uint8 = 0x85 // Keypad Comma
	KeyKeypadEqualSign       uint8 = 0x86 // Keypad Equal Sign
	KeyInternational1        uint8 = 0x87 // Keyboard International1
	KeyInternational2        uint8 = 0x88 // Keyboard International2
	KeyInternational3        uint8 = 0x89 // Keyboard International3
	KeyInternational4        uint8 = 0x8a // Keyboard International4
	KeyInternational5        uint8 = 0x8b // Keyboard International5
	KeyInternational6        uint8 = 0x8c // Keyboard International6
	KeyInternational7        uint8 = 0x8d // Keyboard International7
	KeyInternational8        uint8 = 0x8e // Keyboard International8
	KeyInternational9        uint8 = 0x8f // Keyboard International9
	KeyLang1                 uint8 = 0x90 // Keyboard LANG1
	KeyLang2                 uint8 = 0x91 // Keyboard LANG2
	KeyLang3                 uint8 = 0x92 // Keyboard LANG3
	KeyLang4                 uint8 = 0x93 // Keyboard LANG4
	KeyLang5                 uint8 = 0x94 // Keyboard LANG5
	KeyLang6                 uint8 = 0x95 // Keyboard LANG6
	KeyLang7                 uint8 = 0x96 // Keyboard LANG7
	KeyLang8                 uint8 = 0x97 // Keyboard LANG8
	KeyLang9                 uint8 = 0x98 // Keyboard LANG9
	KeyAlternateErase        uint8 = 0x99 // Keyboard Alternate Erase
	KeyCode9A                uint8 = 0x9a // Keyboard SysReq/Attention
	KeyCancel                uint8 = 0x9b // Keyboard Cancel
	KeyClear                 uint8 = 0x9c // Keyboard Clear
	KeyPrior                 uint8 = 0x9d // Keyboard Prior
	KeyReturn                uint8 = 0x9e // Keyboard Return
	KeySeparator             uint8 = 0x9f // Keyboard Separator
	KeyOut                   uint8 = 0xa0 // Keyboard Out
	KeyOper                  uint8 = 0xa1 // Keyboard Oper
	KeyCodeA2                uint8 = 0xa2 // Keyboard Clear/Again
	KeyCodeA3                uint8 = 0xa3 // Keyboard CrSel/Props
	KeyExSel                 uint8 = 0xa4 // Keyboard ExSel
	KeyKeypad00              uint8 = 0xb0 // Keypad 00
	KeyKeypad000             uint8 = 0xb1 // Keypad 000
	KeyThousandsSeparator    uint8 = 0xb2 // Thousands Separator
	KeyDecimalSeparator      uint8 = 0xb3 // Decimal Separator
	KeyCurrencyUnit          uint8 = 0xb4 // Currency Unit
	KeyCodeB5                uint8 = 0xb5 // Currency Sub-unit
	KeyCodeB6                uint8 = 0xb6 // Keypad (
	KeyCodeB7                uint8 = 0xb7 // Keypad )
	KeyCodeB8                uint8 = 0xb8 // Keypad {
	KeyCodeB9                uint8 = 0xb9 // Keypad }
	KeyKeypadTab             uint8 = 0xba // Keypad Tab
	KeyKeypadBackspace       uint8 = 0xbb // Keypad Backspace
	KeyKeypadA               uint8 = 0xbc // Keypad A
	KeyKeypadB               uint8 = 0xbd // Keypad B
	KeyKeypadC               uint8 = 0xbe // Keypad C
	KeyKeypadD               uint8 = 0xbf // Keypad D
	KeyKeypadE               uint8 = 0xc0 // Keypad E
	KeyKeypadF               uint8 = 0xc1 // Keypad F
	KeyKeypadXor             uint8 = 0xc2 // Keypad XOR
	KeyCodeC3                uint8 = 0xc3 // Keypad ∧
	KeyCodeC4                uint8 = 0xc4 // Keypad %
	KeyCodeC5                uint8 = 0xc5 // Keypad <
	KeyCodeC6                uint8 = 0xc6 // Keypad >
	KeyCodeC7                uint8 = 0xc7 // Keypad &
	KeyCodeC8                uint8 = 0xc8 // Keypad &&
	KeyCodeC9                uint8 = 0xc9 // Keypad \
	KeyCodeCA                uint8 = 0xca // Keypad \
	KeyCodeCB                uint8 = 0xcb // Keypad :
	KeyCodeCC                uint8 = 0xcc // Keypad #
	KeyKeypadSpace           uint8 = 0xcd // Keypad Space
	KeyCodeCE                uint8 = 0xce // Keypad @
	KeyCodeCF                uint8 = 0xcf // Keypad !
	KeyKeypadMemoryStore     uint8 = 0xd0 // Keypad Memory Store
	KeyKeypadMemoryRecall    uint8 = 0xd1 // Keypad Memory Recall
	KeyKeypadMemoryClear     uint8 = 0xd2 // Keypad Memory Clear
	KeyKeypadMemoryAdd       uint8 = 0xd3 // Keypad Memory Add
	KeyKeypadMemorySubtract  uint8 = 0xd4 // Keypad Memory Subtract
	KeyKeypadMemoryMultiply  uint8 = 0xd5 // Keypad Memory Multiply
	KeyKeypadMemoryDivide    uint8 = 0xd6 // Keypad Memory Divide
	KeyCodeD7                uint8 = 0xd7 // Keypad +/-
	KeyKeypadClear           uint8 = 0xd8 // Keypad Clear
	KeyKeypadClearEntry      uint8 = 0xd9 // Keypad Clear Entry
	KeyKeypadBinary          uint8 = 0xda // Keypad Binary
	KeyKeypadOctal           uint8 = 0xdb // Keypad Octal
	KeyKeypadDecimal         uint8 = 0xdc // Keypad Decimal
	KeyKeypadHexadecimal     uint8 = 0xdd // Keypad Hexadecimal
	KeyLeftControl           uint8 = 0xe0 // Keyboard LeftControl
	KeyLeftShift             uint8 = 0xe1 // Keyboard LeftShift
	KeyLeftAlt               uint8 = 0xe2 // Keyboard LeftAlt
	KeyLeftGui               uint8 = 0xe3 // Keyboard LeftGUI
	KeyRightControl          uint8 = 0xe4 // Keyboard RightControl
	KeyRightShift            uint8 = 0xe5 // Keyboard RightShift
	KeyRightAlt              uint8 = 0xe6 // Keyboard RightAlt
	KeyRightGui              uint8 = 0xe7 // Keyboard RightGUI
)

var keyNameMap = map[uint8]string{
	0x1:  "KeyErrorRollOver",
	0x2:  "KeyPostfail",
	0x3:  "KeyErrorUndefined",
	0x4:  "KeyA",
	0x5:  "KeyB",
	0x6:  "KeyC",
	0x7:  "KeyD",
	0x8:  "KeyE",
	0x9:  "KeyF",
	0xa:  "KeyG",
	0xb:  "KeyH",
	0xc:  "KeyI",
	0xd:  "KeyJ",
	0xe:  "KeyK",
	0xf:  "KeyL",
	0x10: "KeyM",
	0x11: "KeyN",
	0x12: "KeyO",
	0x13: "KeyP",
	0x14: "KeyQ",
	0x15: "KeyR",
	0x16: "KeyS",
	0x17: "KeyT",
	0x18: "KeyU",
	0x19: "KeyV",
	0x1a: "KeyW",
	0x1b: "KeyX",
	0x1c: "KeyY",
	0x1d: "KeyZ",
	0x1e: "Key1",
	0x1f: "Key2",
	0x20: "Key3",
	0x21: "Key4",
	0x22: "Key5",
	0x23: "Key6",
	0x24: "Key7",
	0x25: "Key8",
	0x26: "Key9",
	0x27: "Key0",
	0x28: "KeyEnter",
	0x29: "KeyEsc",
	0x2a: "KeyBackspace",
	0x2b: "KeyTab",
	0x2c: "KeySpacebar",
	0x2d: "KeyMinus",
	0x2e: "KeyEqual",
	0x2f: "KeyLeftBracket",
	0x30: "KeyRightBracket",
	0x31: "KeyBackslash",
	0x32: "KeyNonUssharp",
	0x33: "KeySemicolon",
	0x34: "KeyCode34",
	0x35: "KeyGraveAccent",
	0x36: "KeyComma",
	0x37: "KeyPeriod",
	0x38: "KeySlash",
	0x39: "KeyCapsLock",
	0x3a: "KeyF1",
	0x3b: "KeyF2",
	0x3c: "KeyF3",
	0x3d: "KeyF4",
	0x3e: "KeyF5",
	0x3f: "KeyF6",
	0x40: "KeyF7",
	0x41: "KeyF8",
	0x42: "KeyF9",
	0x43: "KeyF10",
	0x44: "KeyF11",
	0x45: "KeyF12",
	0x46: "KeyPrintScreen",
	0x47: "KeyScrollLock",
	0x48: "KeyPause",
	0x49: "KeyInsert",
	0x4a: "KeyHome",
	0x4b: "KeyPageUp",
	0x4c: "KeyDeleteForward",
	0x4d: "KeyEnd",
	0x4e: "KeyPageDown",
	0x4f: "KeyRightArrow",
	0x50: "KeyLeftArrow",
	0x51: "KeyDownArrow",
	0x52: "KeyUpArrow",
	0x53: "KeyKeypadNumLockAndClear",
	0x54: "KeyCode54",
	0x55: "KeyCode55",
	0x56: "KeyCode56",
	0x57: "KeyCode57",
	0x58: "KeyKeypadEnter",
	0x59: "KeyKeypad1AndEnd",
	0x5a: "KeyKeypad2AndDownArrow",
	0x5b: "KeyKeypad3AndPageDn",
	0x5c: "KeyKeypad4AndLeftArrow",
	0x5d: "KeyKeypad5",
	0x5e: "KeyKeypad6AndRightArrow",
	0x5f: "KeyKeypad7AndHome",
	0x60: "KeyKeypad8AndUpArrow",
	0x61: "KeyKeypad9AndPageUp",
	0x62: "KeyKeypad0AndInsert",
	0x63: "KeyCode63",
	0x64: "KeyNonUsbackslash",
	0x65: "KeyApplication",
	0x66: "KeyPower",
	0x67: "KeyCode67",
	0x68: "KeyF13",
	0x69: "KeyF14",
	0x6a: "KeyF15",
	0x6b: "KeyF16",
	0x6c: "KeyF17",
	0x6d: "KeyF18",
	0x6e: "KeyF19",
	0x6f: "KeyF20",
	0x70: "KeyF21",
	0x71: "KeyF22",
	0x72: "KeyF23",
	0x73: "KeyF24",
	0x74: "KeyExecute",
	0x75: "KeyHelp",
	0x76: "KeyMenu",
	0x77: "KeySelect",
	0x78: "KeyStop",
	0x79: "KeyAgain",
	0x7a: "KeyUndo",
	0x7b: "KeyCut",
	0x7c: "KeyCopy",
	0x7d: "KeyPaste",
	0x7e: "KeyFind",
	0x7f: "KeyMute",
	0x80: "KeyVolumeUp",
	0x81: "KeyVolumeDown",
	0x82: "KeyLockingCapsLock",
	0x83: "KeyLockingNumLock",
	0x84: "KeyLockingScrollLock",
	0x85: "KeyKeypadComma",
	0x86: "KeyKeypadEqualSign",
	0x87: "KeyInternational1",
	0x88: "KeyInternational2",
	0x89: "KeyInternational3",
	0x8a: "KeyInternational4",
	0x8b: "KeyInternational5",
	0x8c: "KeyInternational6",
	0x8d: "KeyInternational7",
	0x8e: "KeyInternational8",
	0x8f: "KeyInternational9",
	0x90: "KeyLang1",
	0x91: "KeyLang2",
	0x92: "KeyLang3",
	0x93: "KeyLang4",
	0x94: "KeyLang5",
	0x95: "KeyLang6",
	0x96: "KeyLang7",
	0x97: "KeyLang8",
	0x98: "KeyLang9",
	0x99: "KeyAlternateErase",
	0x9a: "KeyCode9A",
	0x9b: "KeyCancel",
	0x9c: "KeyClear",
	0x9d: "KeyPrior",
	0x9e: "KeyReturn",
	0x9f: "KeySeparator",
	0xa0: "KeyOut",
	0xa1: "KeyOper",
	0xa2: "KeyCodeA2",
	0xa3: "KeyCodeA3",
	0xa4: "KeyExSel",
	0xb0: "KeyKeypad00",
	0xb1: "KeyKeypad000",
	0xb2: "KeyThousandsSeparator",
	0xb3: "KeyDecimalSeparator",
	0xb4: "KeyCurrencyUnit",
	0xb5: "KeyCodeB5",
	0xb6: "KeyCodeB6",
	0xb7: "KeyCodeB7",
	0xb8: "KeyCodeB8",
	0xb9: "KeyCodeB9",
	0xba: "KeyKeypadTab",
	0xbb: "KeyKeypadBackspace",
	0xbc: "KeyKeypadA",
	0xbd: "KeyKeypadB",
	0xbe: "KeyKeypadC",
	0xbf: "KeyKeypadD",
	0xc0: "KeyKeypadE",
	0xc1: "KeyKeypadF",
	0xc2: "KeyKeypadXor",
	0xc3: "KeyCodeC3",
	0xc4: "KeyCodeC4",
	0xc5: "KeyCodeC5",
	0xc6: "KeyCodeC6",
	0xc7: "KeyCodeC7",
	0xc8: "KeyCodeC8",
	0xc9: "KeyCodeC9",
	0xca: "KeyCodeCA",
	0xcb: "KeyCodeCB",
	0xcc: "KeyCodeCC",
	0xcd: "KeyKeypadSpace",
	0xce: "KeyCodeCE",
	0xcf: "KeyCodeCF",
	0xd0: "KeyKeypadMemoryStore",
	0xd1: "KeyKeypadMemoryRecall",
	0xd2: "KeyKeypadMemoryClear",
	0xd3: "KeyKeypadMemoryAdd",
	0xd4: "KeyKeypadMemorySubtract",
	0xd5: "KeyKeypadMemoryMultiply",
	0xd6: "KeyKeypadMemoryDivide",
	0xd7: "KeyCodeD7",
	0xd8: "KeyKeypadClear",
	0xd9: "KeyKeypadClearEntry",
	0xda: "KeyKeypadBinary",
	0xdb: "KeyKeypadOctal",
	0xdc: "KeyKeypadDecimal",
	0xdd: "KeyKeypadHexadecimal",
	0xe0: "KeyLeftControl",
	0xe1: "KeyLeftShift",
	0xe2: "KeyLeftAlt",
	0xe3: "KeyLeftGui",
	0xe4: "KeyRightControl",
	0xe5: "KeyRightShift",
	0xe6: "KeyRightAlt",
	0xe7: "KeyRightGui",
}
