// Code generated by generate-pages. DO NOT EDIT.
package usagepages

const (
	GenericDesktop          uint16 = 0x1    // Generic Desktop Page
	SimulationControls      uint16 = 0x2    // Simulation Controls Page
	VrControls              uint16 = 0x3    // VR Controls Page
	SportControls           uint16 = 0x4    // Sport Controls Page
	GameControls            uint16 = 0x5    // Game Controls Page
	GenericDeviceControls   uint16 = 0x6    // Generic Device Controls Page
	KeyboardKeypad          uint16 = 0x7    // Keyboard/Keypad Page
	Led                     uint16 = 0x8    // LED Page
	Button                  uint16 = 0x9    // Button Page
	Ordinal                 uint16 = 0xa    // Ordinal Page
	TelephonyDevice         uint16 = 0xb    // Telephony Device Page
	Consumer                uint16 = 0xc    // Consumer Page
	Digitizers              uint16 = 0xd    // Digitizers Page
	Haptics                 uint16 = 0xe    // Haptics Page
	PhysicalInputDevice     uint16 = 0xf    // Physical Input Device Page
	Unicode                 uint16 = 0x10   // Unicode Page
	SoC                     uint16 = 0x11   // SoC Page
	EyeAndHeadTrackers      uint16 = 0x12   // Eye and Head Trackers Page
	AuxiliaryDisplay        uint16 = 0x14   // Auxiliary Display Page
	Sensors                 uint16 = 0x20   // Sensors Page
	MedicalInstrument       uint16 = 0x40   // Medical Instrument Page
	BrailleDisplay          uint16 = 0x41   // Braille Display Page
	LightingAndIllumination uint16 = 0x59   // Lighting and Illumination Page
	Monitor                 uint16 = 0x80   // Monitor Page
	MonitorEnumerated       uint16 = 0x81   // Monitor Enumerated Page
	VesaVirtualControls     uint16 = 0x82   // VESA Virtual Controls Page
	Power                   uint16 = 0x84   // Power Page
	BatterySystem           uint16 = 0x85   // Battery System Page
	BarcodeScanner          uint16 = 0x8c   // Barcode Scanner Page
	Scales                  uint16 = 0x8d   // Scales Page
	MagneticStripeReader    uint16 = 0x8e   // Magnetic Stripe Reader
	CameraControl           uint16 = 0x90   // Camera Control Page
	Arcade                  uint16 = 0x91   // Arcade Page
	GamingDevice            uint16 = 0x92   // Gaming Device Page
	FidoAlliance            uint16 = 0xf1d0 // FIDO Alliance Page
)

var pageNameMap = map[uint16]string{
	0x1:    "Generic Desktop Page",
	0x2:    "Simulation Controls Page",
	0x3:    "VR Controls Page",
	0x4:    "Sport Controls Page",
	0x5:    "Game Controls Page",
	0x6:    "Generic Device Controls Page",
	0x7:    "Keyboard/Keypad Page",
	0x8:    "LED Page",
	0x9:    "Button Page",
	0xa:    "Ordinal Page",
	0xb:    "Telephony Device Page",
	0xc:    "Consumer Page",
	0xd:    "Digitizers Page",
	0xe:    "Haptics Page",
	0xf:    "Physical Input Device Page",
	0x10:   "Unicode Page",
	0x11:   "SoC Page",
	0x12:   "Eye and Head Trackers Page",
	0x14:   "Auxiliary Display Page",
	0x20:   "Sensors Page",
	0x40:   "Medical Instrument Page",
	0x41:   "Braille Display Page",
	0x59:   "Lighting and Illumination Page",
	0x80:   "Monitor Page",
	0x81:   "Monitor Enumerated Page",
	0x82:   "VESA Virtual Controls Page",
	0x84:   "Power Page",
	0x85:   "Battery System Page",
	0x8c:   "Barcode Scanner Page",
	0x8d:   "Scales Page",
	0x8e:   "Magnetic Stripe Reader",
	0x90:   "Camera Control Page",
	0x91:   "Arcade Page",
	0x92:   "Gaming Device Page",
	0xf1d0: "FIDO Alliance Page",
}
