name: build

on:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        run: docker buildx build --push -t ghcr.io/neuroplastio/neio-agent:main --platform=linux/amd64,linux/arm64 .
